# Generated by Django 4.2.30 on 2026-08-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internships', models.PositiveIntegerField(default=120)),
                ('publications', models.PositiveIntegerField(default=65)),
                ('hackathon_winners', models.PositiveIntegerField(default=40)),
                ('placement_rate', models.PositiveIntegerField(default=98)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
