# Generated by Django 4.2.30 on 2026-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('placement', 'Placements'), ('research', 'Research & Journals'), ('achievement', 'Achievements'), ('event_archive', 'Events Archive'), ('laboratory', 'Laboratories & Facilities'), ('library', 'Library'), ('alumni', 'Alumni (SHIMMER)'), ('general', 'General')], default='general', max_length=32)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2022-2023, 2021-2023, 2018-2020', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='department_docs/')),
                ('external_url', models.URLField(blank=True, help_text='Direct PDF link from official server if file not uploaded locally', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('computers_count', models.PositiveIntegerField(default=35)),
                ('printers_count', models.PositiveIntegerField(default=3)),
                ('ups_info', models.CharField(default='10 KVA', max_length=100)),
                ('software_installed', models.TextField(default='Oracle, Visual Basic, MS Office, Java')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('metric_value', models.CharField(help_text='e.g. 25+, 149+, 8, 100+, 724+', max_length=50)),
                ('icon', models.CharField(default='fa-solid fa-award', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PlacementStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='e.g. 2023, 2022, 2021...', unique=True)),
                ('students_placed', models.PositiveIntegerField()),
                ('total_offers', models.PositiveIntegerField(blank=True, default=0)),
                ('highest_package', models.CharField(blank=True, default='', max_length=50)),
                ('average_package', models.CharField(blank=True, default='', max_length=50)),
                ('top_recruiters', models.TextField(blank=True, default='TCS, CTS, Wipro, Infosys, Zoho, Accenture, HCL, Cognizant')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
