# Generated by Django 4.2.30 on 2026-08-18 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=260, unique=True)),
                ('category', models.CharField(choices=[('announcement', 'General Announcement'), ('circular', 'Official Circular'), ('placement', 'Placement & Internship'), ('exam', 'Exam & Academics'), ('hackathon', 'Hackathon & Contest'), ('event', 'Event & Workshop')], default='announcement', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='Brief preview summary shown on cards and feeds', max_length=500)),
                ('content', models.TextField(help_text='Detailed news content or circular description')),
                ('is_pinned', models.BooleanField(default=False, help_text='Highlight at top with pulse badge', verbose_name='Urgent / Pinned Bulletin')),
                ('attachment', models.FileField(blank=True, help_text='Optional PDF circular, document or image', null=True, upload_to='news/attachments/%Y/%m/')),
                ('external_link', models.URLField(blank=True, help_text='Optional registration/external reference URL')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
    ]
