# Generated by Django 4.2.30 on 2026-08-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='W3C Push Service endpoint URL', max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Client public key for encryption', max_length=255)),
                ('auth', models.CharField(help_text='Authentication secret', max_length=255)),
                ('user_agent', models.CharField(blank=True, help_text='Browser / OS metadata', max_length=255)),
                ('category_filter', models.CharField(default='all', help_text='Subscribed category filter (e.g. all, placement, circular)', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='last_pushed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last web push broadcast', null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='push_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times push broadcast was sent'),
        ),
    ]
