services:
  - type: web
    name: cse-blog-django
    runtime: docker
    plan: free
    dockerfilePath: ./django_app/Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: ALLOWED_HOSTS
        value: cse-blog-django.onrender.com
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: REDIS_URL
        sync: false
      - key: MEDIA_ROOT
        value: /app/django_app/media
      - key: STATIC_ROOT
        value: /app/django_app/staticfiles
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_REGION_NAME
        value: auto
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
      - key: AWS_QUERYSTRING_AUTH
        value: "false"

  - type: web
    name: cse-blog-fastapi
    runtime: docker
    plan: free
    dockerfilePath: ./fastapi_app/Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
