# Generated by Django 4.2.30 on 2026-08-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('student', 'Student')], default='editor', max_length=16),
        ),
    ]
