# Generated by Django 4.2.30 on 2026-08-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('seminar', 'Seminar'), ('guest_lecture', 'Guest Lecture'), ('symposium', 'Symposium'), ('conference', 'Conference')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='events/%Y/%m/')),
                ('description', models.TextField()),
                ('registration_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
