# Generated by Django 4.2.30 on 2026-08-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('exam', 'Exam / Assessment'), ('hackathon', 'Hackathon / Contest'), ('workshop', 'Workshop / Event'), ('placement', 'Placement Drive'), ('academic', 'Academic Milestone'), ('holiday', 'Holiday / Vacation'), ('deadline', 'Submission Deadline'), ('general', 'General Schedule')], default='academic', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional for multi-day schedules', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('registration_link', models.URLField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='schedules/%Y/%m/')),
                ('is_academic_calendar', models.BooleanField(default=False, help_text='Set to true for official academic calendar items')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_item', to='events.event')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['start_date', 'start_time', 'title'],
            },
        ),
    ]
