# Generated by Django 4.2.30 on 2026-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_link',
            field=models.URLField(blank=True, help_text='External institutional profile URL (e.g. SRM VEC staff page)', max_length=500),
        ),
    ]
