# Generated by Django 4.2.30 on 2026-08-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_link',
            field=models.URLField(blank=True, help_text='IRINS Profile URL (e.g. https://srmvalliammai.irins.org/profile/177877)', max_length=500),
        ),
    ]
